# Generated by Django 6.0 on 2025-12-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_background',
            field=models.ImageField(blank=True, help_text='Upload a 1920x600 image', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='The integrated platform for Blood Donation, Organ Pledging, and Medical Crowdfunding.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Every Drop Counts, Every Penny Helps.', max_length=200),
        ),
    ]
