# Generated by Django 6.0 on 2026-01-30 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galleryimage_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-event_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='blood_units_collected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, help_text='Write what happened, highlights, outcomes, etc.'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='funds_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='people_helped',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='venue',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_how_it_works',
            field=models.TextField(default='• Request created with proof\n• Donors receive notifications\n• Donor responds and donates at hospital\n• Institution verifies donation\n• Eligibility & history updated'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_intro',
            field=models.TextField(default='Share4Life connects donors, recipients, and verified institutions to save lives faster in emergencies.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(default='About Share4Life', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_trust_safety',
            field=models.TextField(default='• Proof required for critical requests\n• Institution verification for trust\n• Privacy-aware contact sharing\n• Audit-friendly history & records'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(default='Lalitpur, Nepal', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='share4life.noreply@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='+977-9849632576', max_length=20),
        ),
    ]
