# Generated by Django 6.0 on 2026-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_galleryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_faq',
            field=models.TextField(blank=True, help_text='FAQ text shown in footer modal (optional).'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_of_service',
            field=models.TextField(blank=True),
        ),
    ]
