# Generated by Django 6.0 on 2026-01-29 13:23

import django.core.validators
import django.db.models.deletion
import organ.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0002_bloodcampaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_type', models.CharField(choices=[('LIVING', 'Living Donation'), ('DECEASED', 'Deceased Donation (after death)')], max_length=10)),
                ('organs', models.JSONField(default=list, help_text='List of organ codes from ORGANS choices')),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('consent_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_pledges', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_pledges_verified_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organ_pledges', to='hospitals.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganPledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('CONSENT_FORM', 'Consent Form'), ('MEDICAL_REPORT', 'Medical Report'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to=organ.models.pledge_doc_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organ.organpledge')),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('organ_needed', models.CharField(choices=[('KIDNEY', 'Kidney'), ('LIVER', 'Liver'), ('HEART', 'Heart'), ('LUNG', 'Lung'), ('PANCREAS', 'Pancreas'), ('INTESTINE', 'Intestine'), ('CORNEA', 'Cornea'), ('SKIN', 'Skin'), ('BONE_MARROW', 'Bone Marrow'), ('OTHER', 'Other')], max_length=20)),
                ('urgency', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('hospital_name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACTIVE', 'Active'), ('MATCH_IN_PROGRESS', 'Match In Progress'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='SUBMITTED', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_requests_created', to=settings.AUTH_USER_MODEL)),
                ('target_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_requests', to='hospitals.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_requests_verified_by', to=settings.AUTH_USER_MODEL)),
                ('verified_by_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_organ_requests', to='hospitals.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONTACTED', 'Contacted'), ('SCREENING', 'Screening'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organ_matches', to='hospitals.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organ_match_updates', to=settings.AUTH_USER_MODEL)),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organ.organpledge')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organ.organrequest')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('MEDICAL_REPORT', 'Medical Report'), ('HOSPITAL_LETTER', 'Hospital Letter'), ('OTHER', 'Other')], default='MEDICAL_REPORT', max_length=20)),
                ('file', models.FileField(upload_to=organ.models.request_doc_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organ.organrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='organpledge',
            index=models.Index(fields=['status', 'created_at'], name='organ_organ_status_c154cd_idx'),
        ),
        migrations.AddIndex(
            model_name='organpledge',
            index=models.Index(fields=['pledge_type', 'status'], name='organ_organ_pledge__e62fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='organrequest',
            index=models.Index(fields=['status', 'created_at'], name='organ_organ_status_d50e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='organrequest',
            index=models.Index(fields=['organ_needed', 'status'], name='organ_organ_organ_n_87929d_idx'),
        ),
        migrations.AddIndex(
            model_name='organmatch',
            index=models.Index(fields=['status', 'updated_at'], name='organ_organ_status_be5580_idx'),
        ),
    ]
