# Generated by Django 6.0 on 2026-01-30 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_bloodcampaign'),
        ('organ', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organmatch',
            constraint=models.UniqueConstraint(fields=('request', 'pledge'), name='uniq_match_per_request_pledge'),
        ),
    ]
