# Generated by Django 6.0 on 2026-02-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organ', '0002_organmatch_uniq_match_per_request_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='organpledge',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
