# Generated by Django 6.0 on 2026-02-02 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0002_campaign_approved_at_campaign_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='esewa_pid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='esewa_ref_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=12),
        ),
        migrations.AlterField(
            model_name='campaignauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONATION_INITIATED', 'Donation Initiated'), ('DONATION_SUCCESS', 'Donation Success'), ('DONATION_FAILED', 'Donation Failed'), ('DISBURSED', 'Disbursed'), ('REPORTED', 'Reported'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('UPDATED', 'Updated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='donation',
            name='gateway',
            field=models.CharField(choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa')], max_length=10),
        ),
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('reason', models.CharField(default='Suspicious', max_length=80)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crowdfunding.campaign')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
