# Generated by Django 6.0 on 2026-02-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_campaign_archived_at_campaign_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='esewa_transaction_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='esewa_transaction_uuid',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
