# Generated by Django 6.0 on 2026-02-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0004_donation_esewa_transaction_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
