# Generated by Django 6.0 on 2026-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0005_campaign_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired (Goal not reached)'), ('ARCHIVED', 'Archived')], default='APPROVED', max_length=12),
        ),
        migrations.AlterField(
            model_name='campaignauditlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DONATION_INITIATED', 'Donation Initiated'), ('DONATION_SUCCESS', 'Donation Success'), ('DONATION_FAILED', 'Donation Failed'), ('DISBURSED', 'Disbursed'), ('REPORTED', 'Reported'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('ARCHIVED', 'Archived'), ('UPDATED', 'Updated')], max_length=30),
        ),
    ]
