# Generated by Django 6.0 on 2026-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kycprofile_kycdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city_canon',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_verified_donation_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='next_eligible_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
