# Generated by Django 6.0 on 2026-02-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_bloodescalationstate_blooddonorpinglog'),
        ('communication', '0002_queuedemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_donor', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='blood.publicbloodrequest')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads_as_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.chatthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['updated_at'], name='communicati_updated_28e2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['last_message_at'], name='communicati_last_me_4f4899_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(fields=('request', 'donor'), name='uniq_chat_thread_request_donor'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='communicati_thread__e9a7db_idx'),
        ),
    ]
