# Generated by Django 6.0 on 2026-02-17 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_chatthread_chatmessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mute_system', models.BooleanField(default=False)),
                ('mute_blood', models.BooleanField(default=False)),
                ('mute_emergency', models.BooleanField(default=False)),
                ('mute_donation', models.BooleanField(default=False)),
                ('mute_campaign', models.BooleanField(default=False)),
                ('mute_kyc', models.BooleanField(default=False)),
                ('mute_chat', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_emergency_only', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('BLOOD', 'Blood'), ('EMERGENCY', 'Emergency'), ('DONATION', 'Donation'), ('CAMPAIGN', 'Campaign'), ('KYC', 'KYC'), ('CHAT', 'Chat')], db_index=True, default='SYSTEM', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='communicati_user_id_63caa7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='communicati_user_id_438b03_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'category', 'created_at'], name='communicati_user_id_9af8b3_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_pref', to=settings.AUTH_USER_MODEL),
        ),
    ]
