"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j)w)mg!wfrc&1@4&%rwf+40ij03mj$f@363e9!2_%kd3bc8gw!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne', # ASGI server
    'jazzmin',  # Admin UI
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # Third Party Libraries
    'channels',         # For InDrive matching

    # Local Apps
    'accounts.apps.AccountsConfig',
    'blood.apps.BloodConfig',
    'communication.apps.CommunicationConfig',
    'core.apps.CoreConfig',
    'crowdfunding.apps.CrowdfundingConfig',
    'hospitals.apps.HospitalsConfig',
    'organ.apps.OrganConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.site_settings',
                'hospitals.context_processors.org_context',
                'communication.context_processors.unread_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        "OPTIONS": {"timeout": 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kathmandu"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / 'static']  #  central static folder

# --- Media Files (Profile Pics, Medical Reports) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Custom User Model ---

AUTH_USER_MODEL = 'accounts.CustomUser'

import os

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", f"Share4Life <{EMAIL_HOST_USER}>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_VERIFICATION_REQUIRED = True

# notification timeout
NOTIFICATION_RETENTION_DAYS = 7

EMAIL_QUEUE_BATCH_SIZE = 40        # safe batch for Gmail sending limits
EMAIL_QUEUE_BATCH_DELAY = 10       # seconds between batches
EMAIL_QUEUE_MAX_ATTEMPTS = 3


ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# Guest emergency anti-spam limits
S4L_GUEST_EMERGENCY_MIN_INTERVAL_SECONDS = 600   # 10 minutes per phone
S4L_GUEST_EMERGENCY_MAX_PER_HOUR_IP = 5          # per IP per hour
S4L_GUEST_EMERGENCY_MAX_PER_HOUR_PHONE = 3       # per phone per hour

# --- reCAPTCHA (Google) ---
RECAPTCHA_SITE_KEY = os.environ.get("RECAPTCHA_SITE_KEY", "")
RECAPTCHA_SECRET_KEY = os.environ.get("RECAPTCHA_SECRET_KEY", "")

# test keys only for local development if real keys are not provided
if DEBUG and (not RECAPTCHA_SITE_KEY or not RECAPTCHA_SECRET_KEY):
    RECAPTCHA_SITE_KEY = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
    RECAPTCHA_SECRET_KEY = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"

RECAPTCHA_ENABLED = bool(RECAPTCHA_SITE_KEY and RECAPTCHA_SECRET_KEY)

# --- Khalti (Sandbox) ---
KHALTI_PUBLIC_KEY = os.environ.get("KHALTI_PUBLIC_KEY", "")
KHALTI_SECRET_KEY = os.environ.get("KHALTI_SECRET_KEY", "")

# Khalti base URL
KHALTI_BASE_URL = os.environ.get("KHALTI_BASE_URL", "https://a.khalti.com/api/v2")
KHALTI_WEBSITE_URL = os.environ.get("KHALTI_WEBSITE_URL", "http://127.0.0.1:8000")

# esewa
ESEWA_PRODUCT_CODE = os.environ.get("ESEWA_PRODUCT_CODE", "EPAYTEST")
ESEWA_SECRET_KEY = os.environ.get("ESEWA_SECRET_KEY", "8gBm/:&EnhH.1/q")

ESEWA_FORM_URL = os.environ.get(
    "ESEWA_FORM_URL",
    "https://rc-epay.esewa.com.np/api/epay/main/v2/form"
)

# After target reached: keep public for 1 day then archive the crowdfunding campaign
CAMPAIGN_ARCHIVE_AFTER_DAYS = int(os.environ.get("CAMPAIGN_ARCHIVE_AFTER_DAYS", "1"))

# reminder for disbursement proof upload (if campaign has raised money but no disbursement record)
DISBURSEMENT_PROOF_REMINDER_DAYS = 3
DISBURSEMENT_PROOF_REMINDER_COOLDOWN_HOURS = 24

# Public feed visibility window (days)
S4L_PUBLIC_FEED_MAX_DAYS = 7

# SOS cooldown so users can't spam institutions
S4L_SOS_COOLDOWN_SECONDS = 600  # 10 minutes

# WhatsApp: default country code for local numbers (Nepal)
S4L_DEFAULT_WHATSAPP_CC = "977"

# Donor reping limits
S4L_EMERGENCY_ESCALATION_MAX_MINUTES = 60   # stop repinging after 60 minutes
S4L_EMERGENCY_REPING_INTERVAL_MINUTES = 1  # how often LOOP runs
S4L_DONOR_REPING_COOLDOWN_SECONDS = 10   # reping after 3 minutes if ignored(need to make change i made it to 10sec to testing )
S4L_DONOR_MAX_REPINGS_PER_REQUEST = 5     # max repings per donor per request