# Generated by Django 6.0 on 2026-01-08 15:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_publicbloodrequest_fulfilled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbloodrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Hospital letter / report / proof document (PDF/JPG/PNG).', null=True, upload_to='blood_request_proofs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified (Guest/No proof)'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=12),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
