# Generated by Django 6.0 on 2026-01-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0003_publicbloodrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbloodrequest',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
