# Generated by Django 6.0 on 2026-01-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_publicbloodrequest_is_emergency'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='verified_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donations', to='hospitals.organization'),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='target_organization',
            field=models.ForeignKey(blank=True, help_text='Which organization should verify/handle this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='hospitals.organization'),
        ),
    ]
