# Generated by Django 6.0 on 2026-01-27 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_blooddonation_verified_by_org_and_more'),
        ('hospitals', '0002_bloodcampaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='blooddonation',
            constraint=models.UniqueConstraint(condition=models.Q(('donor_user__isnull', False), ('request__isnull', False)), fields=('request', 'donor_user'), name='uniq_donation_per_request_per_donor'),
        ),
    ]
