# Generated by Django 6.0 on 2026-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_blooddonation_uniq_donation_per_request_per_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestresponse',
            name='donor_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='publicbloodrequest',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
    ]
