# Generated by Django 6.0 on 2026-01-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_alter_guestresponse_donor_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbloodrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicbloodrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
