# Generated by Django 6.0 on 2026-02-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0008_publicbloodrequest_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbloodrequest',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
    ]
