# Generated by Django 6.0 on 2026-02-10 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0009_publicbloodrequest_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodEscalationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('CITY', 'City'), ('RADIUS_5', 'Radius 5km'), ('RADIUS_10', 'Radius 10km'), ('ORG', 'Notify Organizations'), ('DONE', 'Done')], default='CITY', max_length=12)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_state', to='blood.publicbloodrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BloodDonorPingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('CITY', 'City'), ('RADIUS_5', 'Radius 5km'), ('RADIUS_10', 'Radius 10km'), ('ORG', 'Notify Organizations'), ('DONE', 'Done')], max_length=12)),
                ('pinged_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_ping_logs', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ping_logs', to='blood.publicbloodrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('request', 'donor'), name='uniq_ping_request_donor')],
            },
        ),
    ]
