# Generated by Django 6.0 on 2026-02-13 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_bloodescalationstate_blooddonorpinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonorpinglog',
            name='last_ping_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blooddonorpinglog',
            name='ping_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
