# Generated by Django 6.0 on 2026-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_blooddonorpinglog_last_ping_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicbloodrequest',
            name='location_city_canon',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
