# Generated by Django 6.0 on 2026-03-14 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0012_publicbloodrequest_location_city_canon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodEmailEscalationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('CITY', 'City'), ('NEARBY', 'Nearby/Neighbor Group'), ('RADIUS_10', 'Radius 10km'), ('DONE', 'Done')], default='CITY', max_length=12)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequestEmailedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='donorresponse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='accepted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='donorresponse',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddConstraint(
            model_name='donorresponse',
            constraint=models.UniqueConstraint(fields=('request', 'donor'), name='uniq_donor_response_per_request'),
        ),
        migrations.AddConstraint(
            model_name='donorresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'ACCEPTED')), fields=('request',), name='uniq_primary_accepted_per_request'),
        ),
        migrations.AddField(
            model_name='bloodemailescalationstate',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_state', to='blood.publicbloodrequest'),
        ),
        migrations.AddField(
            model_name='bloodrequestemaileduser',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailed_users', to='blood.publicbloodrequest'),
        ),
        migrations.AddField(
            model_name='bloodrequestemaileduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_emailed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='bloodrequestemaileduser',
            constraint=models.UniqueConstraint(fields=('request', 'user'), name='uniq_email_per_request_user'),
        ),
    ]
