# Generated by Django 6.0 on 2026-04-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0013_bloodemailescalationstate_bloodrequestemaileduser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicbloodrequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='OPEN', max_length=12),
        ),
    ]
