# Generated by Django 6.0 on 2026-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_bloodcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city_canon',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
