# Generated by Django 6.0 on 2026-02-17 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_organization_latitude_organization_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodcampaign',
            name='actual_donors_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcampaign',
            name='actual_units_collected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodcampaign',
            name='completion_report',
            field=models.FileField(blank=True, help_text='Upload proof/report (PDF/JPG/PNG).', null=True, upload_to='campaign_reports/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='bloodcampaign',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='campaign_covers/'),
        ),
        migrations.AddField(
            model_name='bloodcampaign',
            name='impact_highlights',
            field=models.TextField(blank=True),
        ),
    ]
